# Use Node.js as the base image
FROM node:18

# Set the working directory
WORKDIR /app/CareerConnect/backend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy .env file to container

# Expose the port
EXPOSE 5000

# Start the application
CMD ["npm", "start"]
